// XuperTB Localization System
// Multi-language support for geo-compliance

class AppLocale {
  final String code;
  final String name;
  final String nativeName;
  final String flag;
  final Map<String, String> strings;

  const AppLocale({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.flag,
    required this.strings,
  });
}

class Localization {
  static const Map<String, AppLocale> locales = {
    'en': AppLocale(
      code: 'en',
      name: 'English',
      nativeName: 'English',
      flag: '🇬🇧',
      strings: _enStrings,
    ),
    'es': AppLocale(
      code: 'es',
      name: 'Spanish',
      nativeName: 'Español',
      flag: '🇪🇸',
      strings: _esStrings,
    ),
    'pt': AppLocale(
      code: 'pt',
      name: 'Portuguese',
      nativeName: 'Português',
      flag: '🇧🇷',
      strings: _ptStrings,
    ),
    'fr': AppLocale(
      code: 'fr',
      name: 'French',
      nativeName: 'Français',
      flag: '🇫🇷',
      strings: _frStrings,
    ),
    'de': AppLocale(
      code: 'de',
      name: 'German',
      nativeName: 'Deutsch',
      flag: '🇩🇪',
      strings: _deStrings,
    ),
  };

  static const Map<String, String> _enStrings = {
    'live_tv': 'Live TV',
    'movies': 'Movies',
    'series': 'Series',
    'catch_up': 'Catch Up',
    'settings': 'Settings',
    'search': 'Search',
    'all_categories': 'All Categories',
    'search_channels': 'Search channels...',
    'no_channel_selected': 'Select a channel to start',
    'video_error': 'Video can\'t be played',
    'retry': 'Retry',
    'now': 'Now',
    'next': 'Next',
    'favorites': 'Favorites',
    'epg': 'EPG',
    'show_full_epg': 'Show Full EPG',
    'add_remove_categories': 'Add/Remove Categories',
    'vpn_status': 'VPN Status',
    'vpn_connected': 'VPN Connected',
    'vpn_disconnected': 'VPN Disconnected',
    'channel_live': 'Live',
    'channel_offline': 'Offline',
    'speed_test': 'Speed Test',
    'player_settings': 'Player Settings',
    'language': 'Language',
    'epg_url': 'EPG URL',
    'external_player': 'External Player',
    'use_vlc': 'Use VLC Player',
    'use_exoplayer': 'Use ExoPlayer',
    'use_external': 'Use External App',
    'about': 'About',
    'version': 'Version',
  };

  static const Map<String, String> _esStrings = {
    'live_tv': 'TV en Vivo',
    'movies': 'Películas',
    'series': 'Series',
    'catch_up': 'Catch Up',
    'settings': 'Ajustes',
    'search': 'Buscar',
    'all_categories': 'Todas las Categorías',
    'search_channels': 'Buscar canales...',
    'no_channel_selected': 'Selecciona un canal para comenzar',
    'video_error': 'No se puede reproducir el video',
    'retry': 'Reintentar',
    'now': 'Ahora',
    'next': 'Siguiente',
    'favorites': 'Favoritos',
    'epg': 'Guía EPG',
    'show_full_epg': 'Ver Guía Completa',
    'add_remove_categories': 'Gestionar Categorías',
    'vpn_status': 'Estado VPN',
    'vpn_connected': 'VPN Conectada',
    'vpn_disconnected': 'VPN Desconectada',
    'channel_live': 'En Vivo',
    'channel_offline': 'Sin Señal',
    'speed_test': 'Test de Velocidad',
    'player_settings': 'Configuración del Reproductor',
    'language': 'Idioma',
    'epg_url': 'URL de EPG',
    'external_player': 'Reproductor Externo',
    'use_vlc': 'Usar VLC Player',
    'use_exoplayer': 'Usar ExoPlayer',
    'use_external': 'Usar App Externa',
    'about': 'Acerca de',
    'version': 'Versión',
  };

  static const Map<String, String> _ptStrings = {
    'live_tv': 'TV ao Vivo',
    'movies': 'Filmes',
    'series': 'Séries',
    'catch_up': 'Catch Up',
    'settings': 'Configurações',
    'search': 'Buscar',
    'all_categories': 'Todas as Categorias',
    'search_channels': 'Buscar canais...',
    'no_channel_selected': 'Selecione um canal para começar',
    'video_error': 'Não é possível reproduzir o vídeo',
    'retry': 'Tentar novamente',
    'now': 'Agora',
    'next': 'A seguir',
    'favorites': 'Favoritos',
    'epg': 'Guia EPG',
    'show_full_epg': 'Ver Guia Completo',
    'add_remove_categories': 'Gerenciar Categorias',
    'vpn_status': 'Status VPN',
    'vpn_connected': 'VPN Conectada',
    'vpn_disconnected': 'VPN Desconectada',
    'channel_live': 'Ao Vivo',
    'channel_offline': 'Offline',
    'speed_test': 'Teste de Velocidade',
    'player_settings': 'Configurações do Player',
    'language': 'Idioma',
    'epg_url': 'URL do EPG',
    'external_player': 'Player Externo',
    'use_vlc': 'Usar VLC Player',
    'use_exoplayer': 'Usar ExoPlayer',
    'use_external': 'Usar App Externa',
    'about': 'Sobre',
    'version': 'Versão',
  };

  static const Map<String, String> _frStrings = {
    'live_tv': 'TV en Direct',
    'movies': 'Films',
    'series': 'Séries',
    'catch_up': 'Rattrapage',
    'settings': 'Paramètres',
    'search': 'Rechercher',
    'all_categories': 'Toutes les Catégories',
    'search_channels': 'Rechercher des chaînes...',
    'no_channel_selected': 'Sélectionnez une chaîne pour commencer',
    'video_error': 'Impossible de lire la vidéo',
    'retry': 'Réessayer',
    'now': 'En cours',
    'next': 'À suivre',
    'favorites': 'Favoris',
    'epg': 'Guide EPG',
    'show_full_epg': 'Voir Guide Complet',
    'add_remove_categories': 'Gérer les Catégories',
    'vpn_status': 'Statut VPN',
    'vpn_connected': 'VPN Connecté',
    'vpn_disconnected': 'VPN Déconnecté',
    'channel_live': 'En Direct',
    'channel_offline': 'Hors Ligne',
    'speed_test': 'Test de Vitesse',
    'player_settings': 'Paramètres du Lecteur',
    'language': 'Langue',
    'epg_url': 'URL EPG',
    'external_player': 'Lecteur Externe',
    'use_vlc': 'Utiliser VLC Player',
    'use_exoplayer': 'Utiliser ExoPlayer',
    'use_external': 'Utiliser App Externe',
    'about': 'À propos',
    'version': 'Version',
  };

  static const Map<String, String> _deStrings = {
    'live_tv': 'Live TV',
    'movies': 'Filme',
    'series': 'Serien',
    'catch_up': 'Mediathek',
    'settings': 'Einstellungen',
    'search': 'Suche',
    'all_categories': 'Alle Kategorien',
    'search_channels': 'Sender suchen...',
    'no_channel_selected': 'Wählen Sie einen Sender aus',
    'video_error': 'Video kann nicht abgespielt werden',
    'retry': 'Erneut versuchen',
    'now': 'Jetzt',
    'next': 'Als nächstes',
    'favorites': 'Favoriten',
    'epg': 'EPG',
    'show_full_epg': 'Kompletter EPG',
    'add_remove_categories': 'Kategorien verwalten',
    'vpn_status': 'VPN Status',
    'vpn_connected': 'VPN Verbunden',
    'vpn_disconnected': 'VPN Getrennt',
    'channel_live': 'Live',
    'channel_offline': 'Offline',
    'speed_test': 'Geschwindigkeitstest',
    'player_settings': 'Player Einstellungen',
    'language': 'Sprache',
    'epg_url': 'EPG URL',
    'external_player': 'Externer Player',
    'use_vlc': 'VLC Player verwenden',
    'use_exoplayer': 'ExoPlayer verwenden',
    'use_external': 'Externe App verwenden',
    'about': 'Über',
    'version': 'Version',
  };

  static String tr(String key, String locale) {
    return locales[locale]?.strings[key] ?? locales['en']?.strings[key] ?? key;
  }
}
